name: 'Setup environment'

inputs:
  cachePrefix:
    description: 'For correct caching'
    required: false
    default: 'prefix'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@master
      with:
        node-version: 22.11.0

    - name: Print OS name
      run: echo ${{ runner.os }}
      shell: bash

    # https://stackoverflow.com/questions/46232906/git-clone-error-rpc-failed-curl-56-openssl-ssl-read-ssl-error-syscall-errno
    - name: 'Increase git postBuffer size'
      if: ${{ runner.os == 'Windows' }}
      run: git config --global http.postBuffer 524288000
      shell: bash

    # - name: "Set unsafe-perm"
    #   run: npm set unsafe-perm true
    #   shell: bash

    - name: "Install pnpm"
      run: |
        corepack enable
        corepack enable pnpm
        corepack use pnpm@9.12.3
      shell: bash

    - name: "Cache PNPM dependencies"
      id: cache-nodemodules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
        key: ${{ inputs.cachePrefix }}-${{ runner.OS }}-pnpm-cache-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
         ${{ inputs.cachePrefix }}-${{ runner.OS }}-pnpm-cache-

    - name: "Install dependencies"
      if: steps.cache-nodemodules.outputs.cache-hit != 'true'
      run: pnpm i
      shell: bash

    - name: "Build project"
      run: pnpm run build
      shell: bash
