/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import type { ModMetadataResponse, UserValidateResponse } from "./nexusMods.api.types.js";

export interface paths {
  "/v1/games/{game_domain_name}/mods/updated.json": {
    /** <p>Returns a list of mods that have been updated in a given period, with timestamps of their last update. Cached for 5 minutes.</p> */
    get: operations["get_v1_games_game_domain_mods_updates.json"];
  };
  "/v1/games/{game_domain_name}/mods/{mod_id}/changelogs.json": {
    /** <p>Returns list of changelogs for mod</p> */
    get: operations["get_v1_games_game_domain_mods_mod_id_changelogs.json"];
  };
  "/v1/games/{game_domain_name}/mods/latest_added.json": {
    /** <p>Retrieve 10 latest added mods for a specified game</p> */
    get: operations["get_v1_games_game_domain_mods_latest_added.json"];
  };
  "/v1/games/{game_domain_name}/mods/latest_updated.json": {
    /** <p>Retrieve 10 latest updated mods for a specified game</p> */
    get: {
      parameters: {
        path: {
          /** Game Domain E.g. 'skyrim' */
          game_domain_name: string;
        };
      };
      responses: {
        /** Missing */
        404: unknown;
        /** Could not save the entity. */
        422: unknown;
      };
    };
  };
  "/v1/games/{game_domain_name}/mods/trending.json": {
    /** <p>Retrieve 10 trending mods for a specified game</p> */
    get: operations["get_v1_games_game_domain_mods_trending.json"];
  };
  "/v1/games/{game_domain_name}/mods/{id}.json": {
    /** <p>Retrieve specified mod, from a specified game. Cached for 5 minutes.</p> */
    get: operations["get_v1_games_game_domain_name_mods_id.json"];
  };
  "/v1/games/{game_domain_name}/mods/md5_search/{md5_hash}.json": {
    /** <p>Looks up a file MD5 file hash</p> */
    get: operations["get_v1_games_game_domain_name_mods_md5_search_md5_hash.json"];
  };
  "/v1/games/{game_domain_name}/mods/{id}/endorse.json": {
    /** <p>Endorse a mod</p> */
    post: operations["post_v1_games_game_domain_name_mods_id_endorse.json"];
  };
  "/v1/games/{game_domain_name}/mods/{id}/abstain.json": {
    /** <p>Abstain from endorsing a mod</p> */
    post: operations["post_v1_games_game_domain_name_mods_id_abstain.json"];
  };
  "/v1/games/{game_domain_name}/mods/{mod_id}/files.json": {
    /** <p>Lists all files for a specific mod</p> */
    get: operations["get_v1_games_game_domain_mods_mod_id_files.json"];
  };
  "/v1/games/{game_domain_name}/mods/{mod_id}/files/{file_id}.json": {
    /** <p>View a specified mod file, using a specified game and mod</p> */
    get: operations["get_v1_games_game_domain_mods_mod_id_files_file_id.json"];
  };
  "/v1/games/{game_domain_name}/mods/{mod_id}/files/{id}/download_link.json": {
    /**
     * <p>Generate download link for mod file. For premium users, will return array of download links with their prefered download location in the first element.</p><br/>
     *
     * <p>NOTE: Non-premium members must provide the key and expiry from the .nxm link provided by the website. It is recommended for clients to extract them from the nxm link before sending this request. This ensures that all non-premium members must access the website to download through the API.</p>
     */
    get: operations["get_v1_games_game_domain_mods_mod_id_files_id_download_link.json"];
  };
  "/v1/games.json": {
    /**
     * <p>Returns a list of all games. Optionally can also return unapproved
     * games.</p>
     */
    get: operations["get_v1_games.json"];
  };
  "/v1/games/{game_domain_name}.json": {
    /**
     * <p>Returns specified game, along with download count, file count and
     * categories.</p>
     */
    get: operations["get_v1_games_game_domain.json"];
  };
  "/v1/users/validate.json": {
    /** <p>Checks an API key is valid and returns the user&#39;s details.</p> */
    get: operations["post_v1_users_validate.json"];
  };
  "/v1/user/tracked_mods.json": {
    /** <p>Fetch all the mods being tracked by the current user</p> */
    get: operations["get_v1_user_tracked_mods.json"];
    /** <p>Track this mod with the current user</p> */
    post: operations["post_v1_user_tracked_mods.json"];
    /** <p>Stop tracking this mod with the current user</p> */
    delete: operations["delete_v1_user_tracked_mods.json"];
  };
  "/v1/user/endorsements.json": {
    /** <p>Returns a list of all endorsements for the current user.</p> */
    get: operations["get_v1_user_endorsements.json"];
  };
  "/v1/colourschemes.json": {
    /**
     * <p>Returns list of all colour schemes, including the primary, secondary and
     * &#39;darker&#39; colours.</p>
     */
    get: operations["get_v1_colourschemes.json"];
  };
}

export interface definitions {}

export interface operations {
  /** <p>Returns a list of mods that have been updated in a given period, with timestamps of their last update. Cached for 5 minutes.</p> */
  "get_v1_games_game_domain_mods_updates.json": {
    parameters: {
      query: {
        /** The only accepted periods are 1d, 1w and 1m (1 day, 1 week and 1 month) */
        period: string;
      };
      path: {
        /** Game Domain E.g. 'skyrim' */
        game_domain_name: string;
      };
    };
    responses: {
      /** ok */
      200: unknown;
    };
  };
  /** <p>Returns list of changelogs for mod</p> */
  "get_v1_games_game_domain_mods_mod_id_changelogs.json": {
    parameters: {
      path: {
        mod_id: number;
        /** Game Domain E.g. 'skyrim' */
        game_domain_name: string;
      };
    };
    responses: {
      /** ok */
      200: unknown;
    };
  };
  /** <p>Retrieve 10 latest added mods for a specified game</p> */
  "get_v1_games_game_domain_mods_latest_added.json": {
    parameters: {
      path: {
        /** Game Domain E.g. 'skyrim' */
        game_domain_name: string;
      };
    };
    responses: {
      /** Missing */
      404: unknown;
      /** Could not save the entity. */
      422: unknown;
    };
  };
  /** <p>Retrieve 10 trending mods for a specified game</p> */
  "get_v1_games_game_domain_mods_trending.json": {
    parameters: {
      path: {
        /** Game Domain E.g. 'skyrim' */
        game_domain_name: string;
      };
    };
    responses: {
      /** Missing */
      404: unknown;
      /** Could not save the entity. */
      422: unknown;
    };
  };
  /** <p>Retrieve specified mod, from a specified game. Cached for 5 minutes.</p> */
  "get_v1_games_game_domain_name_mods_id.json": {
    parameters: {
      path: {
        /** Mod ID */
        id: number;
        /** Game Domain E.g. 'skyrim' */
        game_domain_name: string;
      };
    };
    responses: {
      /** Missing */
      404: unknown;
      /** Could not save the entity. */
      422: unknown;
    };
  };
  /** <p>Looks up a file MD5 file hash</p> */
  "get_v1_games_game_domain_name_mods_md5_search_md5_hash.json": {
    parameters: {
      path: {
        /** Mod ID */
        md5_hash: string;
        /** Game Domain E.g. 'skyrim' */
        game_domain_name: string;
      };
    };
    responses: {
      /** Missing */
      404: unknown;
      /** Could not save the entity. */
      422: unknown;
      /** Mod found */
      200: {
        schema: ModMetadataResponse[]
      }
    };
  };
  /** <p>Endorse a mod</p> */
  "post_v1_games_game_domain_name_mods_id_endorse.json": {
    parameters: {
      path: {
        /** Game Domain E.g. 'skyrim' */
        game_domain_name: string;
        /** Mod ID */
        id: number;
      };
      formData: {
        /** Mod Version */
        version?: string;
      };
    };
    responses: {
      /** Invalid Request */
      400: unknown;
      /** Missing */
      404: unknown;
      /** Could not save the entity. */
      422: unknown;
    };
  };
  /** <p>Abstain from endorsing a mod</p> */
  "post_v1_games_game_domain_name_mods_id_abstain.json": {
    parameters: {
      path: {
        /** Game Domain E.g. 'skyrim' */
        game_domain_name: string;
        /** Mod ID */
        id: number;
      };
      formData: {
        /** Mod Version */
        version?: string;
      };
    };
    responses: {
      /** Invalid Request */
      400: unknown;
      /** Missing */
      404: unknown;
      /** Could not save the entity. */
      422: unknown;
    };
  };
  /** <p>Lists all files for a specific mod</p> */
  "get_v1_games_game_domain_mods_mod_id_files.json": {
    parameters: {
      path: {
        /** Game Domain E.g. 'skyrim' */
        game_domain_name: string;
        /** Mod ID */
        mod_id: number;
      };
      query: {
        /** Filter File Category. Case insensitive. Comma seperated list of categories. Can be: main, update, optional, old_version or miscellaneous */
        category?: string;
      };
    };
    responses: {
      /** Missing Resource */
      404: unknown;
    };
  };
  /** <p>View a specified mod file, using a specified game and mod</p> */
  "get_v1_games_game_domain_mods_mod_id_files_file_id.json": {
    parameters: {
      path: {
        /** File ID */
        file_id: number;
        /** Game Domain Name E.g. skyrim */
        game_domain_name: string;
        /** Mod ID */
        mod_id: number;
      };
    };
    responses: {
      /** Missing Resource */
      404: unknown;
    };
  };
  /**
   * <p>Generate download link for mod file. For premium users, will return array of download links with their prefered download location in the first element.</p><br/>
   *
   * <p>NOTE: Non-premium members must provide the key and expiry from the .nxm link provided by the website. It is recommended for clients to extract them from the nxm link before sending this request. This ensures that all non-premium members must access the website to download through the API.</p>
   */
  "get_v1_games_game_domain_mods_mod_id_files_id_download_link.json": {
    parameters: {
      path: {
        /** Game Domain Name E.g. skyrim */
        game_domain_name: string;
        /** File ID */
        id: number;
        /** Mod ID */
        mod_id: number;
      };
      query: {
        /** Key provided by Nexus Mods Website */
        key?: string;
        /** Expiry of the key */
        expires?: number;
      };
    };
    responses: {
      /** Provided key and expire time isn't correct for this user/file. */
      400: unknown;
      /** You don't have permission to get download links from the API without visting nexusmods.com - this is for premium users only. */
      403: unknown;
      /** File not found. */
      404: unknown;
      /** This link has expired - please visit the mod page again to get a new link. */
      410: unknown;
    };
  };
  /**
   * <p>Returns a list of all games. Optionally can also return unapproved
   * games.</p>
   */
  "get_v1_games.json": {
    parameters: {
      query: {
        /** Whether to include unapproved games or not */
        include_unapproved?: boolean;
      };
    };
    responses: {
      /** Missing */
      404: unknown;
      /** Could not save the entity. */
      422: unknown;
    };
  };
  /**
   * <p>Returns specified game, along with download count, file count and
   * categories.</p>
   */
  "get_v1_games_game_domain.json": {
    parameters: {
      path: {
        /** Game Domain Name E.g. skyrim */
        game_domain_name: string;
      };
    };
    responses: {
      /** Missing */
      404: unknown;
      /** Could not save the entity. */
      422: unknown;
    };
  };
  /** <p>Checks an API key is valid and returns the user&#39;s details.</p> */
  "post_v1_users_validate.json": {
    parameters: {};
    responses: {
      /** Missing */
      404: unknown;
      /** Could not save the entity. */
      422: unknown;
      /** User found */
      200: {
        schema: UserValidateResponse;
      };
    };
  };
  /** <p>Fetch all the mods being tracked by the current user</p> */
  "get_v1_user_tracked_mods.json": {
    parameters: {};
    responses: {
      /** Missing */
      404: unknown;
    };
  };
  /** <p>Track this mod with the current user</p> */
  "post_v1_user_tracked_mods.json": {
    parameters: {
      query: {
        /** Game Domain Name E.g. skyrim */
        domain_name: string;
      };
      formData: {
        /** The ID of the Mod to track */
        mod_id: number;
      };
    };
    responses: {
      /** User already tracking mod */
      200: unknown;
      /** User succesfully tracked mod */
      201: unknown;
    };
  };
  /** <p>Stop tracking this mod with the current user</p> */
  "delete_v1_user_tracked_mods.json": {
    parameters: {
      query: {
        /** Game Domain Name E.g. skyrim */
        domain_name: string;
      };
      formData: {
        /** The ID of the Mod to stop tracking */
        mod_id: number;
      };
    };
    responses: {
      /** Missing */
      404: unknown;
    };
  };
  /** <p>Returns a list of all endorsements for the current user.</p> */
  "get_v1_user_endorsements.json": {
    responses: {
      /** Success */
      200: unknown;
      /** Valid API key not provided */
      401: unknown;
      /** Missing */
      404: unknown;
      /** Could not save the entity. */
      422: unknown;
    };
  };
  /**
   * <p>Returns list of all colour schemes, including the primary, secondary and
   * &#39;darker&#39; colours.</p>
   */
  "get_v1_colourschemes.json": {
    parameters: {};
    responses: {
      /** ok */
      200: unknown;
    };
  };
}

export interface external {}
